//
//  Nag.swift
//  FischerCore
//
//  Created by Omar Megdadi on 1/4/25.
//

///Numeric Annotation Glyph
enum NAG: Int, CaseIterable, Equatable {
    case nullAnnotation = 0
    case goodMove
    case poorMove
    case veryGoodMove
    case veryPoorMove
    case speculativeMove
    case questionableMove
    case forcedMove
    case singularMove
    case worstMove
    case drawishPosition
    case equalChancesQuiet
    case equalChancesActive
    case unclearPosition
    case whiteSlightAdvantage
    case blackSlightAdvantage
    case whiteModerateAdvantage
    case blackModerateAdvantage
    case whiteDecisiveAdvantage
    case blackDecisiveAdvantage
    case whiteCrushingAdvantage
    case blackCrushingAdvantage
    case whiteZugzwang
    case blackZugzwang
    case whiteSlightSpace
    case blackSlightSpace
    case whiteModerateSpace
    case blackModerateSpace
    case whiteDecisiveSpace
    case blackDecisiveSpace
    case whiteSlightTime
    case blackSlightTime
    case whiteModerateTime
    case blackModerateTime
    case whiteDecisiveTime
    case blackDecisiveTime
    case whiteInitiative
    case blackInitiative
    case whiteLastingInitiative
    case blackLastingInitiative
    case whiteAttack
    case blackAttack
    case whiteInsufficientCompensation
    case blackInsufficientCompensation
    case whiteSufficientCompensation
    case blackSufficientCompensation
    case whiteMoreThanAdequateCompensation
    case blackMoreThanAdequateCompensation
    case whiteSlightCenterControl
    case blackSlightCenterControl
    case whiteModerateCenterControl
    case blackModerateCenterControl
    case whiteDecisiveCenterControl
    case blackDecisiveCenterControl
    case whiteSlightKingsideControl
    case blackSlightKingsideControl
    case whiteModerateKingsideControl
    case blackModerateKingsideControl
    case whiteDecisiveKingsideControl
    case blackDecisiveKingsideControl
    case whiteSlightQueensideControl
    case blackSlightQueensideControl
    case whiteModerateQueensideControl
    case blackModerateQueensideControl
    case whiteDecisiveQueensideControl
    case blackDecisiveQueensideControl
    case whiteVulnerableFirstRank
    case blackVulnerableFirstRank
    case whiteProtectedFirstRank
    case blackProtectedFirstRank
    case whitePoorKingSafety
    case blackPoorKingSafety
    case whiteGoodKingSafety
    case blackGoodKingSafety
    case whitePoorKingPlacement
    case blackPoorKingPlacement
    case whiteGoodKingPlacement
    case blackGoodKingPlacement
    case whiteVeryWeakPawnStructure
    case blackVeryWeakPawnStructure
    case whiteModeratelyWeakPawnStructure
    case blackModeratelyWeakPawnStructure
    case whiteModeratelyStrongPawnStructure
    case blackModeratelyStrongPawnStructure
    case whiteVeryStrongPawnStructure
    case blackVeryStrongPawnStructure
    case whitePoorKnightPlacement
    case blackPoorKnightPlacement
    case whiteGoodKnightPlacement
    case blackGoodKnightPlacement
    case whitePoorBishopPlacement
    case blackPoorBishopPlacement
    case whiteGoodBishopPlacement
    case blackGoodBishopPlacement
    case whitePoorRookPlacement
    case blackPoorRookPlacement
    case whiteGoodRookPlacement
    case blackGoodRookPlacement
    case whitePoorQueenPlacement
    case blackPoorQueenPlacement
    case whiteGoodQueenPlacement
    case blackGoodQueenPlacement
    case whitePoorCoordination
    case blackPoorCoordination
    case whiteGoodCoordination
    case blackGoodCoordination
    case whiteVeryPoorOpening
    case blackVeryPoorOpening
    case whitePoorOpening
    case blackPoorOpening
    case whiteGoodOpening
    case blackGoodOpening
    case whiteVeryGoodOpening
    case blackVeryGoodOpening
    case whiteVeryPoorMiddlegame
    case blackVeryPoorMiddlegame
    case whitePoorMiddlegame
    case blackPoorMiddlegame
    case whiteGoodMiddlegame
    case blackGoodMiddlegame
    case whiteVeryGoodMiddlegame
    case blackVeryGoodMiddlegame
    case whiteVeryPoorEndgame
    case blackVeryPoorEndgame
    case whitePoorEndgame
    case blackPoorEndgame
    case whiteGoodEndgame
    case blackGoodEndgame
    case whiteVeryGoodEndgame
    case blackVeryGoodEndgame
    case whiteSlightCounterplay
    case blackSlightCounterplay
    case whiteModerateCounterplay
    case blackModerateCounterplay
    case whiteDecisiveCounterplay
    case blackDecisiveCounterplay
    case whiteModerateTimePressure
    case blackModerateTimePressure
    case whiteSevereTimePressure
    case blackSevereTimePressure
}
