//
//  CountryCode.swift
//  FischerCore
//
//  Created by Omar Megdadi on 1/4/25.
//

enum CountryCode: String, CustomStringConvertible, CaseIterable, Equatable {
    case afg = "AFG"
    case air = "AIR"
    case alb = "ALB"
    case alg = "ALG"
    case and = "AND"
    case ang = "ANG"
    case ant = "ANT"
    case arg = "ARG"
    case arm = "ARM"
    case ata = "ATA"
    case aus = "AUS"
    case azb = "AZB"
    case ban = "BAN"
    case bar = "BAR"
    case bhm = "BHM"
    case bel = "BEL"
    case ber = "BER"
    case bih = "BIH"
    case bla = "BLA"
    case blg = "BLG"
    case blz = "BLZ"
    case bol = "BOL"
    case brb = "BRB"
    case brs = "BRS"
    case bru = "BRU"
    case bsw = "BSW"
    case can = "CAN"
    case chi = "CHI"
    case col = "COL"
    case cra = "CRA"
    case cro = "CRO"
    case csr = "CSR"
    case cub = "CUB"
    case cyp = "CYP"
    case den = "DEN"
    case dom = "DOM"
    case ecu = "ECU"
    case egy = "EGY"
    case eng = "ENG"
    case esp = "ESP"
    case est = "EST"
    case fai = "FAI"
    case fij = "FIJ"
    case fin = "FIN"
    case fra = "FRA"
    case gam = "GAM"
    case gci = "GCI"
    case geo = "GEO"
    case ger = "GER"
    case gha = "GHA"
    case grc = "GRC"
    case gua = "GUA"
    case guy = "GUY"
    case hai = "HAI"
    case hkg = "HKG"
    case hon = "HON"
    case hun = "HUN"
    case ind = "IND"
    case irl = "IRL"
    case irn = "IRN"
    case irq = "IRQ"
    case isd = "ISD"
    case isr = "ISR"
    case ita = "ITA"
    case ivo = "IVO"
    case jam = "JAM"
    case jap = "JAP"
    case jrd = "JRD"
    case jug = "JUG"
    case kaz = "KAZ"
    case ken = "KEN"
    case kir = "KIR"
    case kuw = "KUW"
    case lat = "LAT"
    case leb = "LEB"
    case lib = "LIB"
    case lic = "LIC"
    case ltu = "LTU"
    case lux = "LUX"
    case mal = "MAL"
    case mau = "MAU"
    case mex = "MEX"
    case mli = "MLI"
    case mlt = "MLT"
    case mnc = "MNC"
    case mol = "MOL"
    case mon = "MON"
    case moz = "MOZ"
    case mrc = "MRC"
    case mrt = "MRT"
    case myn = "MYN"
    case ncg = "NCG"
    case net = "NET"
    case nig = "NIG"
    case nla = "NLA"
    case nld = "NLD"
    case nor = "NOR"
    case nzd = "NZD"
    case ost = "OST"
    case pak = "PAK"
    case pal = "PAL"
    case pan = "PAN"
    case par = "PAR"
    case per = "PER"
    case phi = "PHI"
    case png = "PNG"
    case pol = "POL"
    case por = "POR"
    case prc = "PRC"
    case pro = "PRO"
    case qtr = "QTR"
    case rin = "RIN"
    case rom = "ROM"
    case rus = "RUS"
    case saf = "SAF"
    case sal = "SAL"
    case sco = "SCO"
    case sea = "SEA"
    case sen = "SEN"
    case sey = "SEY"
    case sip = "SIP"
    case slv = "SLV"
    case sma = "SMA"
    case spc = "SPC"
    case sri = "SRI"
    case sud = "SUD"
    case sur = "SUR"
    case sve = "SVE"
    case swz = "SWZ"
    case syr = "SYR"
    case tai = "TAI"
    case tmt = "TMT"
    case trk = "TRK"
    case tto = "TTO"
    case tun = "TUN"
    case uae = "UAE"
    case uga = "UGA"
    case ukr = "UKR"
    case unk = "UNK"
    case uru = "URU"
    case usa = "USA"
    case uzb = "UZB"
    case ven = "VEN"
    case vgb = "VGB"
    case vie = "VIE"
    case vus = "VUS"
    case wls = "WLS"
    case yem = "YEM"
    case yug = "YUG"
    case zam = "ZAM"
    case zim = "ZIM"
    case zre = "ZRE"

//    var description: String {
//        switch self {
//        case .afg: return "Afghanistan"
//        case .air: return "Aboard aircraft"
//        case .alb: return "Albania"
//        case .alg: return "Algeria"
//        case .and: return "Andorra"
//        case .ang: return "Angola"
//        case .ant: return "Antigua"
//        case .arg: return "Argentina"
//        case .arm: return "Armenia"
//        case .ata: return "Antarctica"
//        case .aus: return "Australia"
//        case .azb: return "Azerbaijan"
//        case .ban: return "Bangladesh"
//        case .bar: return "Bahrain"
//        case .bhm: return "Bahamas"
//        case .bel: return "Belgium"
//        case .ber: return "Bermuda"
//        case .bih: return "Bosnia and Herzegovina"
//        case .bla: return "Belarus"
//        case .blg: return "Bulgaria"
//        case .blz: return "Belize"
//        case .bol: return "Bolivia"
//        case .brb: return "Barbados"
//        case .brs: return "Brazil"
//        case .bru: return "Brunei"
//        case .bsw: return "Botswana"
//        case .can: return "Canada"
//        case .chi: return "Chile"
//        case .col: return "Columbia"
//        case .cra: return "Costa Rica"
//        case .cro: return "Croatia"
//        case .csr: return "Czechoslovakia"
//        case .cub: return "Cuba"
//        case .cyp: return "Cyprus"
//        case .den: return "Denmark"
//        case .dom: return "Dominican Republic"
//        case .ecu: return "Ecuador"
//        case .egy: return "Egypt"
//        case .eng: return "England"
//        case .esp: return "Spain"
//        case .est: return "Estonia"
//        case .fai: return "Faroe Islands"
//        case .fij: return "Fiji"
//        case .fin: return "Finland"
//        case .fra: return "France"
//        case .gam: return "Gambia"
//        case .gci: return "Guernsey-Jersey"
//        case .geo: return "Georgia"
//        case .ger: return "Germany"
//        case .gha: return "Ghana"
//        case .grc: return "Greece"
//        case .gua: return "Guatemala"
//        case .guy: return "Guyana"
//        case .hai: return "Haiti"
//        case .hkg: return "Hong Kong"
//        case .hon: return "Honduras"
//        case .hun: return "Hungary"
//        case .ind: return "India"
//        case .irl: return "Ireland"
//        case .irn: return "Iran"
//        case .irq: return "Iraq"
//        case .isd: return "Iceland"
//        case .isr: return "Israel"
//        case .ita: return "Italy"
//        case .ivo: return "Ivory Coast"
//        case .jam: return "Jamaica"
//        case .jap: return "Japan"
//        case .jrd: return "Jordan"
//        case .jug: return "Yugoslavia"
//        case .kaz: return "Kazakhstan"
//        case .ken: return "Kenya"
//        case .kir: return "Kyrgyzstan"
//        case .kuw: return "Kuwait"
//        case .lat: return "Latvia"
//        case .leb: return "Lebanon"
//        case .lib: return "Libya"
//        case .lic: return "Liechtenstein"
//        case .ltu: return "Lithuania"
//        case .lux: return "Luxembourg"
//        case .mal: return "Malaysia"
//        case .mau: return "Mauritania"
//        case .mex: return "Mexico"
//        case .mli: return "Mali"
//        case .mlt: return "Malta"
//        case .mnc: return "Monaco"
//        case .mol: return "Moldova"
//        case .mon: return "Mongolia"
//        case .moz: return "Mozambique"
//        case .mrc: return "Morocco"
//        case .mrt: return "Mauritius"
//        case .myn: return "Myanmar"
//        case .ncg: return "Nicaragua"
//        case .net: return "The Internet"
//        case .nig: return "Nigeria"
//        case .nla: return "Netherlands Antilles"
//        case .nld: return "Netherlands"
//        case .nor: return "Norway"
//        case .nzd: return "New Zealand"
//        case .ost: return "Austria"
//        case .pak: return "Pakistan"
//        case .pal: return "Palestine"
//        case .pan: return "Panama"
//        case .par: return "Paraguay"
//        case .per: return "Peru"
//        case .phi: return "Philippines"
//        case .png: return "Papua New Guinea"
//        case .pol: return "Poland"
//        case .por: return "Portugal"
//        case .prc: return "People's Republic of China"
//        case .pro: return "Puerto Rico"
//        case .qtr: return "Qatar"
//        case .rin: return "Indonesia"
//        case .rom: return "Romania"
//        case .rus: return "Russia"
//        case .saf: return "South Africa"
//        case .sal: return "El Salvador"
//        case .sco: return "Scotland"
//        case .sea: return "At Sea"
//        case .sen: return "Senegal"
//        case .sey: return "Seychelles"
//        case .sip: return "Singapore"
//        case .slv: return "Slovenia"
//        case .sma: return "San Marino"
//        case .spc: return "Aboard spacecraft"
//        case .sri: return "Sri Lanka"
//        case .sud: return "Sudan"
//        case .sur: return "Surinam"
//        case .sve: return "Sweden"
//        case .swz: return "Switzerland"
//        case .syr: return "Syria"
//        case .tai: return "Thailand"
//        case .tmt: return "Turkmenistan"
//        case .trk: return "Turkey"
//        case .tto: return "Trinidad and Tobago"
//        case .tun: return "Tunisia"
//        case .uae: return "United Arab Emirates"
//        case .uga: return "Uganda"
//        case .ukr: return "Ukraine"
//        case .unk: return "Unknown"
//        case .uru: return "Uruguay"
//        case .usa: return "United States of America"
//        case .uzb: return "Uzbekistan"
//        case .ven: return "Venezuela"
//        case .vgb: return "British Virgin Islands"
//        case .vie: return "Vietnam"
//        case .vus: return "U.S. Virgin Islands"
//        case .wls: return "Wales"
//        case .yem: return "Yemen"
//        case .yug: return "Yugoslavia"
//        case .zam: return "Zambia"
//        case .zim: return "Zimbabwe"
//        case .zre: return "Zaire"
//        }
//    }
}
